#!/bin/sh

export GJS_PATH="/usr/local/share/books/js${GJS_PATH:+:$GJS_PATH}"
export GI_TYPELIB_PATH="/usr/local/lib/books/girepository-1.0${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}"
export LD_LIBRARY_PATH="/usr/local/lib/books${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

if test x"$GJS_DEBUG_OUTPUT" = x ; then
    export GJS_DEBUG_OUTPUT=stderr
fi

if test x"$GJS_DEBUG_TOPICS" = x ; then
    export GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
fi

DEBUG_COMMAND=""
if test x"$BOOKS_RUN_DEBUG" != x; then
    DEBUG_COMMAND="gdb --args"
fi

exec $DEBUG_COMMAND /usr/bin/gjs-console -I /usr/local/share/books/js -c "const Main = imports.main; Main.start();" "$@"